/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'odahiroshi' at '16/12/09 10:01' with Gradle 3.2.1
 *
 * @author odahiroshi, @date 16/12/09 10:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
